// <auto-generated />
namespace HiringManager.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MakePositionOpenDateRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakePositionOpenDateRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201404172244396_MakePositionOpenDateRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
