// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Web.Mvc;
using T4MVC;
namespace HiringManager.Web.Areas.HelpPage.Controllers
{
    public partial class HelpController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HelpController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Api()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Api);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HelpController Actions { get { return MVC.HelpPage.Help; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "HelpPage";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Help";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Help";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Api = "Api";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Api = "Api";
        }


        static readonly ActionParamsClass_Api s_params_Api = new ActionParamsClass_Api();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Api ApiParams { get { return s_params_Api; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Api
        {
            public readonly string apiId = "apiId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Api = "Api";
                public readonly string Index = "Index";
            }
            public readonly string Api = "~/Areas/HelpPage/Views/Help/Api.cshtml";
            public readonly string Index = "~/Areas/HelpPage/Views/Help/Index.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string ApiGroup = "ApiGroup";
                public readonly string HelpPageApiModel = "HelpPageApiModel";
                public readonly string ImageSample = "ImageSample";
                public readonly string InvalidSample = "InvalidSample";
                public readonly string Parameters = "Parameters";
                public readonly string Samples = "Samples";
                public readonly string TextSample = "TextSample";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HelpController : HiringManager.Web.Areas.HelpPage.Controllers.HelpController
    {
        public T4MVC_HelpController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void ApiOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string apiId);

        public override System.Web.Mvc.ActionResult Api(string apiId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Api);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "apiId", apiId);
            ApiOverride(callInfo, apiId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
